apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-api
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-api
  template:
    metadata:
      labels:
        app: simple-python-api
    spec:
      containers:
      - name: simple-python-api
        image: simple-python-api
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-api
  namespace: apis
spec:
  selector:
    app: simple-python-api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
