name: "CI: Python"

on: [push]

jobs:
  build:
    uses: mlschuweiler/cicd-workflows/.github/workflows/ci-python.yaml@main
    secrets: inherit
    with:
      additional_pytest_options: "--cov=src/ tests/"